### ISSUE TITLE
Project Report

### ISSUE THREAD

**Issue by ivanvc** [go-js-yourself/gjsy#6]
From the Final project page

>     a project report, as a PDF file, containing the information below.  In addition to the work turned in, each group will give a brief  presentation and demo of their code.

> You may create a separate git repository if you prefer that. Your final report should have 4 sections:
>
> Overview
> Describe the motivation, goals, and broad accomplishments of your project in general terms.
>
> Implementation
> A brief description of the important aspects of your implementation, in  terms of (a) the major tasks or capabilities of your code; (b)  components of the code; (d) status of the project – what works well,  what works partially, and and what is not implemented at all. You MUST  compare these with your original proposed goals in the project proposal.
>
> Tests
> Coming up with appropriate tests is one of the most important part of  good software development. Your tests should include unit tests, feature  tests, and larger test codes. Give a short description of the tests  used, performance results if appropriate (e.g., memory consumption for  garbage collection) etc. Be sure to explain how these tests exercise the  concept(s) you've implemented.
> 
> Listing
> A listing of your code. The code should be documented thoroughly and  clearly. You don't need to comment every single line or even every  single function. Instead, focus on the central functions and data  structures in your implementation, and document them well.

**Comment by milespossing** [comment]
Complete
